# --- Configuration for the News2Alpha Pipeline ---

# 1. Data Ingestion Parameters
news:
  source: 'newsapi' # 'cryptopanic' or 'newsapi'
  query: 'Bitcoin' # The keyword to search for
  from_date: '2025-06-09'
  to_date: '2025-07-09'

market:
  symbol: 'BTCUSDT'       # The trading pair symbol for Binance
  interval: '15m'           # The K-line interval for Binance (e.g., 1m, 5m, 1h, 1d)
